const stands = {
  "1": {name: "CLAAS Bordesholm GmbH Standort", area: "Landtechnik & Maschinenbau"},
"2": {name: "Europa-Universität Flensburg", area: "Hochschule & Bildung"},
"3": {name: "Ramelow", area: "Einzelhandel"},
"4": {name: "Schleswig-Holstein Netz", area: "Energieversorgung"},
"5": {name: "CM-Automation", area: "Industrieautomation"},
"6": {name: "Fachhochschule Westküste", area: "Hochschule & Bildung"},
"7": {name: "Steuerberatergesellschaft ttp", area: "Steuerberatung"},
"8": {name: "Galabau", area: "Garten- & Landschaftsbau"},
"9": {name: "Campus Suderburg", area: "Hochschule & Bildung"},
"10": {name: "Stadtwerke Heide", area: "Energie & Versorgung"},
"11": {name: "Kreishandwerkerschaft Dithmarschen", area: "Handwerksorganisation"},
"12": {name: "Will-Bau", area: "Baugewerbe"},
"13": {name: "Hochschule Wismar", area: "Hochschule & Bildung"},
"14": {name: "Finanzamt Dithmarschen", area: "Öffentliche Verwaltung"},
"15": {name: "DFDS Baltic Seaways", area: "Schifffahrt & Logistik"},
"16": {name: "Landesamt für Vermessung und Geoinformation S-H", area: "Öffentliche Verwaltung & Geoinformation"},
"17": {name: "Kreis Dithmarschen", area: "Kommunalverwaltung"},
"18": {name: "Aldi", area: "Lebensmitteleinzelhandel"},
"19": {name: "Deich- und Hauptsielverband Dithmarschen", area: "Wasserwirtschaft"},
"20": {name: "Dithmarscher Volks- und Raiffeisenbank", area: "Bankwesen"},
"21": {name: "DRK-Akademie", area: "Gesundheitsausbildung"},
"22": {name: "Landwirtschaftskammer SH", area: "Landwirtschaft & Beratung"},
"23": {name: "Medizinische Schule HH", area: "Gesundheitsausbildung"},
"24": {name: "Sasol", area: "Chemische Industrie"},
"25": {name: "Schröder Bauzentrum", area: "Baustoffhandel"},
"26": {name: "amedes-group", area: "Medizinische Diagnostik"},
"27": {name: "Bundespolizei", area: "Sicherheitsbehörde"},
"28": {name: "Westhof Bio", area: "Lebensmittelproduktion"},
"29": {name: "Christoph Heide", area: "Dienstleistungen"},
"30": {name: "Georg C", area: "Dienstleistungen"},
"31": {name: "HAW Kiel", area: "Hochschule & Bildung"},
"32": {name: "Yara", area: "Chemische Industrie"},
"33": {name: "Bundeswehr", area: "Verteidigung"},
"34": {name: "Zahnärztekammer", area: "Berufsorganisation Gesundheit"},
"35": {name: "Heinemann", area: "Einzelhandel"},
"36": {name: "TKMS", area: "Schiffbau & Rüstungsindustrie"},
"37": {name: "Nordakademie Elmshorn", area: "Hochschule & duale Bildung"},
"38": {name: "Justizvollzugsschule", area: "Öffentliche Ausbildung"},
"39": {name: "Hotel Küstenperle", area: "Hotellerie & Tourismus"},
"40": {name: "Stolz", area: "Einzelhandel"},
"41": {name: "Nordseemilch Witzwort", area: "Lebensmittelproduktion"},
"42": {name: "Oberlandesgericht", area: "Justiz"},
"43": {name: "Bundesagentur für Arbeit und Jugendberufsagentur", area: "Arbeitsmarkt & öffentliche Verwaltung"},
"44": {name: "Anhalt Logistics", area: "Logistik"},
"45": {name: "Apothekerkammer", area: "Berufsorganisation Gesundheit"},
"46": {name: "Köster", area: "Bauunternehmen"},
"47": {name: "Raffinerie Hemmingstedt", area: "Energie & Raffinerie"},
"48": {name: "Boyens Medien", area: "Medien & Verlag"},
"49": {name: "Nissen Elektrobau", area: "Elektrotechnik"},
"50": {name: "WKK", area: "Gesundheitswesen"},
"51": {name: "Uni Kiel", area: "Hochschule & Bildung"},
"52": {name: "Eurodesk/ Kreisjugendring Stormarn", area: "Jugend- & Bildungsarbeit"},
"53": {name: "Duale Hochschule SH", area: "Hochschule & duale Bildung"},
"54": {name: "Strabag", area: "Bauunternehmen"},
"55": {name: "Rechtsanwaltskammer", area: "Berufsorganisation Recht"},
"56": {name: "Fielmann", area: "Augenoptik & Einzelhandel"},
"57": {name: "Lidl", area: "Lebensmitteleinzelhandel"},
"58": {name: "Enercon", area: "Windenergie & Anlagenbau"},
"59": {name: "Kardell-Sothmann", area: "Handwerk"},
"60": {name: "Deutsche Bahn", area: "Schienenverkehr"},
"61": {name: "AOK", area: "Krankenversicherung"},
"62": {name: "Göpfert", area: "Maschinenbau"},
"63": {name: "Landespolizei", area: "Sicherheitsbehörde"},
"64": {name: "Sparkasse Westholstein", area: "Bankwesen"},
"65": {name: "Stadt Heide", area: "Kommunalverwaltung"},
"66": {name: "IHK Flensburg", area: "Wirtschaftsorganisation"},
"67": {name: "Zoll", area: "Finanz- & Sicherheitsbehörde"},
"68": {name: "Volks- und Raiffeisenbank SH Mitte", area: "Bankwesen"},
"69": {name: "Scheller Boyens", area: "Rechtsberatung"},
"70": {name: "Schornsteinfegerinnung", area: "Handwerksorganisation"},
"71": {name: "Schutzstation Wattenmeer / Umweltjahr / FÖJ", area: "Umwelt- & Naturschutz"}


};
